In [3]:
url = "https://raw.githubusercontent.com/albertyw/avenews/master/old/data/average-latitude-longitude-countries.csv"
import pandas as pd
df_latlng = pd.read_csv(url)
df_latlng

    ISO 3166 Country Code               Country  Latitude  Longitude
0                      AD               Andorra     42.50       1.50
1                      AE  United Arab Emirates     24.00      54.00
2                      AF           Afghanistan     33.00      65.00
3                      AG   Antigua and Barbuda     17.05     -61.80
4                      AI              Anguilla     18.25     -63.17
..                    ...                   ...       ...        ...
235                    YE                 Yemen     15.00      48.00
236                    YT               Mayotte    -12.83      45.17
237                    ZA          South Africa    -29.00      24.00
238                    ZM                Zambia    -15.00      30.00
239                    ZW              Zimbabwe    -20.00      30.00

[240 rows x 4 columns]

In [5]:
data = "data.csv"
df = pd.read_csv(data)
df.head()

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),text,AFR,Africa,Country,LSO,Lesotho,Year,2019,...,NaN,NaN,NaN,NaN,NaN,42.3,NaN,NaN,EN,2020-12-04T05:00:00.000Z
1,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),text,AFR,Africa,Country,LSO,Lesotho,Year,2019,...,NaN,NaN,NaN,NaN,NaN,44.2,NaN,NaN,EN,2020-12-04T05:00:00.000Z
2,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),text,AFR,Africa,Country,CAF,Central African Republic,Year,2019,...,NaN,NaN,NaN,NaN,NaN,44.5,NaN,NaN,EN,2020-12-04T05:00:00.000Z
3,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),text,AFR,Africa,Country,CAF,Central African Republic,Year,2019,...,NaN,NaN,NaN,NaN,NaN,46.4,NaN,NaN,EN,2020-12-04T05:00:00.000Z
4,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),text,AFR,Africa,Country,LSO,Lesotho,Year,2019,...,NaN,NaN,NaN,NaN,NaN,46.4,NaN,NaN,EN,2020-12-04T05:00:00.000Z

In [13]:
column_names = df.columns.values.tolist()
column_names

['IndicatorCode',
 'Indicator',
 'ValueType',
 'ParentLocationCode',
 'ParentLocation',
 'Location type',
 'SpatialDimValueCode',
 'Location',
 'Period type',
 'Period',
 'IsLatestYear',
 'Dim1 type',
 'Dim1',
 'Dim1ValueCode',
 'Dim2 type',
 'Dim2',
 'Dim2ValueCode',
 'Dim3 type',
 'Dim3',
 'Dim3ValueCode',
 'DataSourceDimValueCode',
 'DataSource',
 'FactValueNumericPrefix',
 'FactValueNumeric',
 'FactValueUoM',
 'FactValueNumericLowPrefix',
 'FactValueNumericLow',
 'FactValueNumericHighPrefix',
 'FactValueNumericHigh',
 'Value',
 'FactValueTranslationID',
 'FactComments',
 'Language',
 'DateModified']

In [ ]:
rename_df = df_latlng.df_latlng()

In [14]:
merge_df = pd.merge(df, df_latlng,  how = 'left', left_on[""])
merge_df

SyntaxError: positional argument follows keyword argument (330579632.py, line 1)