In [24]:
url = "https://raw.githubusercontent.com/albertyw/avenews/master/old/data/average-latitude-longitude-countries.csv"
import pandas as pd
df_latlng = pd.read_csv(url)
df_latlng

    ISO 3166 Country Code               Country  Latitude  Longitude
0                      AD               Andorra     42.50       1.50
1                      AE  United Arab Emirates     24.00      54.00
2                      AF           Afghanistan     33.00      65.00
3                      AG   Antigua and Barbuda     17.05     -61.80
4                      AI              Anguilla     18.25     -63.17
..                    ...                   ...       ...        ...
235                    YE                 Yemen     15.00      48.00
236                    YT               Mayotte    -12.83      45.17
237                    ZA          South Africa    -29.00      24.00
238                    ZM                Zambia    -15.00      30.00
239                    ZW              Zimbabwe    -20.00      30.00

[240 rows x 4 columns]

In [25]:
data = "data.csv"
df = pd.read_csv(data)
df.head()

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),text,AFR,Africa,Country,LSO,Lesotho,Year,2019,...,NaN,NaN,NaN,NaN,NaN,42.3,NaN,NaN,EN,2020-12-04T05:00:00.000Z
1,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),text,AFR,Africa,Country,LSO,Lesotho,Year,2019,...,NaN,NaN,NaN,NaN,NaN,44.2,NaN,NaN,EN,2020-12-04T05:00:00.000Z
2,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),text,AFR,Africa,Country,CAF,Central African Republic,Year,2019,...,NaN,NaN,NaN,NaN,NaN,44.5,NaN,NaN,EN,2020-12-04T05:00:00.000Z
3,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),text,AFR,Africa,Country,CAF,Central African Republic,Year,2019,...,NaN,NaN,NaN,NaN,NaN,46.4,NaN,NaN,EN,2020-12-04T05:00:00.000Z
4,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),text,AFR,Africa,Country,LSO,Lesotho,Year,2019,...,NaN,NaN,NaN,NaN,NaN,46.4,NaN,NaN,EN,2020-12-04T05:00:00.000Z

In [26]:
column_names = df.columns.values.tolist()
column_names

['IndicatorCode',
 'Indicator',
 'ValueType',
 'ParentLocationCode',
 'ParentLocation',
 'Location type',
 'SpatialDimValueCode',
 'Location',
 'Period type',
 'Period',
 'IsLatestYear',
 'Dim1 type',
 'Dim1',
 'Dim1ValueCode',
 'Dim2 type',
 'Dim2',
 'Dim2ValueCode',
 'Dim3 type',
 'Dim3',
 'Dim3ValueCode',
 'DataSourceDimValueCode',
 'DataSource',
 'FactValueNumericPrefix',
 'FactValueNumeric',
 'FactValueUoM',
 'FactValueNumericLowPrefix',
 'FactValueNumericLow',
 'FactValueNumericHighPrefix',
 'FactValueNumericHigh',
 'Value',
 'FactValueTranslationID',
 'FactComments',
 'Language',
 'DateModified']

In [27]:
rename_df = df.rename(columns={"Location": "Country"})
rename_df

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Country,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),text,AFR,Africa,Country,LSO,Lesotho,Year,2019,...,NaN,NaN,NaN,NaN,NaN,42.30,NaN,NaN,EN,2020-12-04T05:00:00.000Z
1,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),text,AFR,Africa,Country,LSO,Lesotho,Year,2019,...,NaN,NaN,NaN,NaN,NaN,44.20,NaN,NaN,EN,2020-12-04T05:00:00.000Z
2,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),text,AFR,Africa,Country,CAF,Central African Republic,Year,2019,...,NaN,NaN,NaN,NaN,NaN,44.50,NaN,NaN,EN,2020-12-04T05:00:00.000Z
3,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),text,AFR,Africa,Country,CAF,Central African Republic,Year,2019,...,NaN,NaN,NaN,NaN,NaN,46.40,NaN,NaN,EN,2020-12-04T05:00:00.000Z
4,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),text,AFR,Africa,Country,LSO,Lesotho,Year,2019,...,NaN,NaN,NaN,NaN,NaN,46.40,NaN,NaN,EN,2020-12-04T05:00:00.000Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4387,WHOSIS_000007,Healthy life expectancy (HALE) at age 60 (years),text,AFR,Africa,Country,ERI,Eritrea,Year,2000,...,NaN,NaN,NaN,NaN,NaN,9.88,NaN,NaN,EN,2020-12-04T05:00:00.000Z
4388,WHOSIS_000007,Healthy life expectancy (HALE) at age 60 (years),text,AFR,Africa,Country,SWZ,Eswatini,Year,2000,...,NaN,NaN,NaN,NaN,NaN,9.92,NaN,NaN,EN,2020-12-04T05:00:00.000Z
4389,WHOSIS_000007,Healthy life expectancy (HALE) at age 60 (years),text,EUR,Europe,Country,RUS,Russian Federation,Year,2000,...,NaN,NaN,NaN,NaN,NaN,9.92,NaN,NaN,EN,2020-12-04T05:00:00.000Z
4390,WHOSIS_000007,Healthy life expectancy (HALE) at age 60 (years),text,AFR,Africa,Country,BDI,Burundi,Year,2000,...,NaN,NaN,NaN,NaN,NaN,9.93,NaN,NaN,EN,2020-12-04T05:00:00.000Z
4391,WHOSIS_000007,Healthy life expectancy (HALE) at age 60 (years),text,AFR,Africa,Country,CAF,Central African Republic,Year,2000,...,NaN,NaN,NaN,NaN,NaN,9.97,NaN,NaN,EN,2020-12-04T05:00:00.000Z

In [28]:
merge_df = pd.merge(rename_df, df_latlng,  how = 'left', on="Country")
merge_df

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Country,Period type,Period,...,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified,ISO 3166 Country Code,Latitude,Longitude
0,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),text,AFR,Africa,Country,LSO,Lesotho,Year,2019,...,NaN,NaN,42.30,NaN,NaN,EN,2020-12-04T05:00:00.000Z,LS,-29.5,28.5
1,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),text,AFR,Africa,Country,LSO,Lesotho,Year,2019,...,NaN,NaN,44.20,NaN,NaN,EN,2020-12-04T05:00:00.000Z,LS,-29.5,28.5
2,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),text,AFR,Africa,Country,CAF,Central African Republic,Year,2019,...,NaN,NaN,44.50,NaN,NaN,EN,2020-12-04T05:00:00.000Z,CF,7.0,21.0
3,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),text,AFR,Africa,Country,CAF,Central African Republic,Year,2019,...,NaN,NaN,46.40,NaN,NaN,EN,2020-12-04T05:00:00.000Z,CF,7.0,21.0
4,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),text,AFR,Africa,Country,LSO,Lesotho,Year,2019,...,NaN,NaN,46.40,NaN,NaN,EN,2020-12-04T05:00:00.000Z,LS,-29.5,28.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4387,WHOSIS_000007,Healthy life expectancy (HALE) at age 60 (years),text,AFR,Africa,Country,ERI,Eritrea,Year,2000,...,NaN,NaN,9.88,NaN,NaN,EN,2020-12-04T05:00:00.000Z,ER,15.0,39.0
4388,WHOSIS_000007,Healthy life expectancy (HALE) at age 60 (years),text,AFR,Africa,Country,SWZ,Eswatini,Year,2000,...,NaN,NaN,9.92,NaN,NaN,EN,2020-12-04T05:00:00.000Z,NaN,NaN,NaN
4389,WHOSIS_000007,Healthy life expectancy (HALE) at age 60 (years),text,EUR,Europe,Country,RUS,Russian Federation,Year,2000,...,NaN,NaN,9.92,NaN,NaN,EN,2020-12-04T05:00:00.000Z,RU,60.0,100.0
4390,WHOSIS_000007,Healthy life expectancy (HALE) at age 60 (years),text,AFR,Africa,Country,BDI,Burundi,Year,2000,...,NaN,NaN,9.93,NaN,NaN,EN,2020-12-04T05:00:00.000Z,BI,-3.5,30.0
4391,WHOSIS_000007,Healthy life expectancy (HALE) at age 60 (years),text,AFR,Africa,Country,CAF,Central African Republic,Year,2000,...,NaN,NaN,9.97,NaN,NaN,EN,2020-12-04T05:00:00.000Z,CF,7.0,21.0

In [29]:
column_names = merge_df.columns.values.tolist()
column_names

['IndicatorCode',
 'Indicator',
 'ValueType',
 'ParentLocationCode',
 'ParentLocation',
 'Location type',
 'SpatialDimValueCode',
 'Country',
 'Period type',
 'Period',
 'IsLatestYear',
 'Dim1 type',
 'Dim1',
 'Dim1ValueCode',
 'Dim2 type',
 'Dim2',
 'Dim2ValueCode',
 'Dim3 type',
 'Dim3',
 'Dim3ValueCode',
 'DataSourceDimValueCode',
 'DataSource',
 'FactValueNumericPrefix',
 'FactValueNumeric',
 'FactValueUoM',
 'FactValueNumericLowPrefix',
 'FactValueNumericLow',
 'FactValueNumericHighPrefix',
 'FactValueNumericHigh',
 'Value',
 'FactValueTranslationID',
 'FactComments',
 'Language',
 'DateModified',
 'ISO 3166 Country Code',
 'Latitude',
 'Longitude']

In [30]:
#merge_df.to_csv(r"C:\Users\Brian Keffer\GW Bootcamp\Project-3\merged_data.csv", index=False)

In [33]:
final_data_df = merge_df.rename(columns={"Indicator": "HALE", "Period":"Year","Value": "Age Expectancy", "Dim1":"Sex"})
final_data_df

,IndicatorCode,HALE,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Country,Period type,Year,...,FactValueNumericHighPrefix,FactValueNumericHigh,Age Expectancy,FactValueTranslationID,FactComments,Language,DateModified,ISO 3166 Country Code,Latitude,Longitude
0,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),text,AFR,Africa,Country,LSO,Lesotho,Year,2019,...,NaN,NaN,42.30,NaN,NaN,EN,2020-12-04T05:00:00.000Z,LS,-29.5,28.5
1,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),text,AFR,Africa,Country,LSO,Lesotho,Year,2019,...,NaN,NaN,44.20,NaN,NaN,EN,2020-12-04T05:00:00.000Z,LS,-29.5,28.5
2,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),text,AFR,Africa,Country,CAF,Central African Republic,Year,2019,...,NaN,NaN,44.50,NaN,NaN,EN,2020-12-04T05:00:00.000Z,CF,7.0,21.0
3,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),text,AFR,Africa,Country,CAF,Central African Republic,Year,2019,...,NaN,NaN,46.40,NaN,NaN,EN,2020-12-04T05:00:00.000Z,CF,7.0,21.0
4,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),text,AFR,Africa,Country,LSO,Lesotho,Year,2019,...,NaN,NaN,46.40,NaN,NaN,EN,2020-12-04T05:00:00.000Z,LS,-29.5,28.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4387,WHOSIS_000007,Healthy life expectancy (HALE) at age 60 (years),text,AFR,Africa,Country,ERI,Eritrea,Year,2000,...,NaN,NaN,9.88,NaN,NaN,EN,2020-12-04T05:00:00.000Z,ER,15.0,39.0
4388,WHOSIS_000007,Healthy life expectancy (HALE) at age 60 (years),text,AFR,Africa,Country,SWZ,Eswatini,Year,2000,...,NaN,NaN,9.92,NaN,NaN,EN,2020-12-04T05:00:00.000Z,NaN,NaN,NaN
4389,WHOSIS_000007,Healthy life expectancy (HALE) at age 60 (years),text,EUR,Europe,Country,RUS,Russian Federation,Year,2000,...,NaN,NaN,9.92,NaN,NaN,EN,2020-12-04T05:00:00.000Z,RU,60.0,100.0
4390,WHOSIS_000007,Healthy life expectancy (HALE) at age 60 (years),text,AFR,Africa,Country,BDI,Burundi,Year,2000,...,NaN,NaN,9.93,NaN,NaN,EN,2020-12-04T05:00:00.000Z,BI,-3.5,30.0
4391,WHOSIS_000007,Healthy life expectancy (HALE) at age 60 (years),text,AFR,Africa,Country,CAF,Central African Republic,Year,2000,...,NaN,NaN,9.97,NaN,NaN,EN,2020-12-04T05:00:00.000Z,CF,7.0,21.0

In [47]:
# This needs to be done after renaming the columns appropriately for the columns we want. Turned into a DF
# After this export as a new csv for final use
final_data = final_data_df[["HALE", "Country", "Year", "Sex", "Age Expectancy", "Latitude", "Longitude"]]
final_data

,HALE,Country,Year,Sex,Age Expectancy,Latitude,Longitude
0,Healthy life expectancy (HALE) at birth (years),Lesotho,2019,Male,42.30,-29.5,28.5
1,Healthy life expectancy (HALE) at birth (years),Lesotho,2019,Both sexes,44.20,-29.5,28.5
2,Healthy life expectancy (HALE) at birth (years),Central African Republic,2019,Male,44.50,7.0,21.0
3,Healthy life expectancy (HALE) at birth (years),Central African Republic,2019,Both sexes,46.40,7.0,21.0
4,Healthy life expectancy (HALE) at birth (years),Lesotho,2019,Female,46.40,-29.5,28.5
...,...,...,...,...,...,...,...
4387,Healthy life expectancy (HALE) at age 60 (years),Eritrea,2000,Both sexes,9.88,15.0,39.0
4388,Healthy life expectancy (HALE) at age 60 (years),Eswatini,2000,Both sexes,9.92,NaN,NaN
4389,Healthy life expectancy (HALE) at age 60 (years),Russian Federation,2000,Male,9.92,60.0,100.0
4390,Healthy life expectancy (HALE) at age 60 (years),Burundi,2000,Both sexes,9.93,-3.5,30.0
4391,Healthy life expectancy (HALE) at age 60 (years),Central African Republic,2000,Female,9.97,7.0,21.0

In [48]:
final_data.to_csv(r"C:\Users\Brian Keffer\GW Bootcamp\Project-3\final_data.csv", index=False)